### PR TITLE
SLING-12419: Snapshot dependencies in discovery.impl

### PR DESCRIPTION
**Pull request by mreutegg**
Update to released versions of discovery.base and discovery.commons.
Update commons.scheduler dependency required by discovery.base.
Fix HeartbeatTest after dependency updates.

### CODE REVIEW

**Review by reschke — APPROVED** [review]
LGTM.

**Review by rombert — COMMENTED** [review]
Looks good, thanks. Why did you disable SonarQube checks?

**Comment by mreutegg** [comment]
> Why did you disable SonarQube checks?

It seems this project is not configured on sonarcloud.io and the build fails with:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project org.apache.sling.discovery.impl: Could not find a default branch for project with key 'apache_sling-org-apache-sling-discovery-impl'. Make sure project exists. -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project org.apache.sling.discovery.impl: Could not find a default branch for project with key 'apache_sling-org-apache-sling-discovery-impl'. Make sure project exists.
```

**Review by rombert — APPROVED** [review]

**Comment by rombert** [comment]
> > Why did you disable SonarQube checks?
> 
> It seems this project is not configured on sonarcloud.io and the build fails with:
> 
> ```
> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project org.apache.sling.discovery.impl: Could not find a default branch for project with key 'apache_sling-org-apache-sling-discovery-impl'. Make sure project exists. -> [Help 1]
> 
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project org.apache.sling.discovery.impl: Could not find a default branch for project with key 'apache_sling-org-apache-sling-discovery-impl'. Make sure project exists.
> ```

Makes sense to disable it, indeed. Will re-enable after https://issues.apache.org/jira/browse/SLING-12423 is solved.

Thanks for the contribution.

**Pull request merged**
