### PR TITLE
SLING-12458: Migrate discovery.impl to Resource Observation API

### PR DESCRIPTION
**Pull request by mreutegg**
Replace usage of OSGi events with Resource Observation API
Update Sling API to 2.11.0, which introduced the Resource Observation API
Remove now obsolete org.osgi.service.event dependency

### CODE REVIEW

**Review by stefan-egli — APPROVED** [review]
+1, lgtm

while the log.info for topology changes should not have been overly noisy, it is probably indeed more of a debug kind of log. so +1 to lower that.

**Comment by mreutegg** [comment]
Strange, I specifically added a test for ClusterViewChangeListener, but SonarCloud still reports no lines covered. I can see 90% line coverage after running the new test locally.

**Comment by enapps-enorman** [comment]
> Strange, I specifically added a test for ClusterViewChangeListener, but SonarCloud still reports no lines covered. I can see 90% line coverage after running the new test locally.

@mreutegg It looks to me like the jacoco arguments are not being passed to the maven-surefire-plugin. This seems to be due to this pom overriding the argLine configuration of the maven-surefire-plugin which overwrites what the parent pom was doing to pass the jacoco arguments to the test runner.

Changing it to something like below to merge what was in the parent with the local values should work:
`<argLine>-Xmx2048m ${jacoco.ut.command}</argLine>`

If you run maven locally with the jacoco-report profile enabled, you should see the reports generated under target/site
`mvn clean install -P jacoco-report`

**Comment by mreutegg** [comment]
@enapps-enorman, thanks for the hint. It works locally after adding `${jacoco.ut.command}` to `argLine`. The report is generated under `target/site`, but it doesn't seem to work on Jenkins. The build fails with this change...

**Comment by enapps-enorman** [comment]
> @enapps-enorman, thanks for the hint. It works locally after adding `${jacoco.ut.command}` to `argLine`. The report is generated under `target/site`, but it doesn't seem to work on Jenkins. The build fails with this change...

@mreutegg Sorry about that.  It looks like the jenkins build is now failing on the attempts that do not use the jacoco-report profile because the jacoco.ut.command system property was never defined in that scenario.  That jenkins build uses the jacoco-report profile only for the java11 variant.  For the other java17 and java21 variants it does not do the code coverage analysis again so it does not try to use the jacoco-report profile.

So, I guess it will need a more elaborate solution.  

The build seems to work for me in both scenarios if I just remove the `<argLine>-Xmx2048m</argLine>` configuration.  But I don't know enough about this project to know if changing the max memory is important for some reason.

**Comment by mreutegg** [comment]
Thanks for your help, @enapps-enorman. I changed the pom.xml to consider the jacoco-report profile when overriding argLine for the surefire plugin. This seems to work and jacoco related options are only added when the profile is enabled.

**Comment by rombert** [comment]
@mreutegg - the module, in the state before your PR, overwrote some the `maven-surefire-plugin` configurations for the `jacoco-report` profile. Looks like you figured that out and restored the correct behaviour, thanks!

**Comment by stefan-egli** [comment]
@mreutegg , nice we got sonar working again! I guess the PR is ready to merge, should I do that?

**Comment by mreutegg** [comment]
> I guess the PR is ready to merge, should I do that?

Yes, please.

**Comment by stefan-egli** [comment]
done

**Pull request merged**
